### ISSUE TITLE
Improve CHANGELOG order

### ISSUE THREAD

**Issue by deandreamatias** [incrediblezayed/file_saver#1]
A good practice in changelog, place last version in first place

Expected order:

```
## 0.0.5

* Minor Bug Fixes

## 0.0.4

* saveFile method returns the path where the file is saved.

... older versions
```

Current order:

```
... older versions

## 0.0.4

* saveFile method returns the path where the file is saved.

## 0.0.5

* Minor Bug Fixes
```

**Comment by incrediblezayed** [comment]
> A good practice in changelog, place last version in first place
> 
> Expected order:
> 
> ```
> ## 0.0.5
> 
> * Minor Bug Fixes
> 
> ## 0.0.4
> 
> * saveFile method returns the path where the file is saved.
> 
> ... older versions
> ```
> 
> Current order:
> 
> ```
> ... older versions
> 
> ## 0.0.4
> 
> * saveFile method returns the path where the file is saved.
> 
> ## 0.0.5
> 
> * Minor Bug Fixes
> ```

Will do it asap

**Comment by incrediblezayed** [comment]
Done, thanks again for mentioning ❤️❤️❤️
