### ISSUE TITLE
Mac OS generated code issue

### ISSUE THREAD

**Issue by rockingdice** [incrediblezayed/file_saver#10]
![image](https://user-images.githubusercontent.com/3458134/127416243-ce602d57-ad71-47ec-bfeb-30c8958ed0c2.png)

I cannot use this plugin on Mac OS:
```
Target of URI doesn't exist: 'package:file_saver/file_saver_web.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.dart(uri_does_not_exist)
```

**Comment by incrediblezayed** [comment]
Please run flutter clean and flutter pub upgrade with latest version of plugin (0.0.10)

**Comment by incrediblezayed** [comment]
The issue is fixed.
