### ISSUE TITLE
type 'String' is not a subtype of type 'Uint8List' 

### ISSUE THREAD

**Issue by ninjagaru** [incrediblezayed/file_saver#105]
Before upgrading to Flutter 3.19.2 and Dart 3.3.0, everything ran perfectly. However, after the upgrade, I encountered the error: type 'String' is not a subtype of type 'Uint8List'.

  file_saver: ^0.2.11

[✓] Flutter (Channel stable, 3.19.2, on macOS 14.2.1 23C71 darwin-x64, locale en-US)
    • Flutter version 3.19.2 on channel stable at /Users/hsDev/fvm/versions/3.19.2
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7482962148 (5 days ago), 2024-02-27 16:51:22 -0500
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

**Comment by Am3ra** [comment]
Running into the same issue on my end

**Comment by NishadAvnish** [comment]
use this parameter: 

transformDioResponse: (path) {
          print(path);

          List<int> list = utf8.encode(path);
          Uint8List bytes = Uint8List.fromList(list);
          return bytes;
        },

**Comment by Am3ra** [comment]
yeah, that would fix it, sadly I was pressed for time so just downgraded the version

**Comment by incrediblezayed** [comment]
I'll upgrade within this week, apologies for such trivial issues

**Comment by incrediblezayed** [comment]
Hey, fixed this issue in the lates version, closing now

**Comment by ninjagaru** [comment]
> Hey, fixed this issue in the lates version, closing now

THANK A LOT

**Comment by Am3ra** [comment]
@incrediblezayed no problem :) thanks for the quick fix!
