### ISSUE TITLE
saveFile option not saving .srt file to downloads folder on android

### ISSUE THREAD

**Issue by premingiet** [incrediblezayed/file_saver#11]
saveFile option not saving .srt file to downloads folder on android. Also on using saveAs option on android, the extension is not applied when file is saved. It is just saving with filename and no extension. I am using MimeType.OTHER and also using .srt as ext type,

**Comment by premingiet** [comment]
i also checked the repository and found this code, where implementation for android section is missing. it has for iOS, MacOs, Windows and Linux but i dont see Android in it.
```dart
 Future<String?> _getDirectory() async {
    String? _path = "";
    try {
      if (Platform.isIOS) {
        _path = (await path.getApplicationDocumentsDirectory()).path;
      } else if (Platform.isMacOS) {
        _path = (await path.getDownloadsDirectory())?.path;
      } else if (Platform.isWindows) {
        pathProvderWindows.PathProviderWindows pathWindows =
            pathProvderWindows.PathProviderWindows();
        _path = await pathWindows.getDownloadsPath();
      } else if (Platform.isLinux) {
        pathProviderLinux.PathProviderLinux pathLinux =
            pathProviderLinux.PathProviderLinux();
        _path = await pathLinux.getDownloadsPath();
      }
    } on Exception catch (e) {
      print("Something wemt worng while getting directories");
      print(e);
    }
    return _path;
  }
```

**Comment by incrediblezayed** [comment]
For android, I have implemented a different approach and due to security reasons I had to change the location of file to Android/data/your.app.package/files.  If you want any other directory please use saveAs method

**Comment by incrediblezayed** [comment]
Please check as I told you.
