### ISSUE TITLE
iOS: Button "Move" instead of "Save"

### ISSUE THREAD

**Issue by slawekkaw** [incrediblezayed/file_saver#111]
When the user tries to saveAs in iOS, the dialog app pop up and  the user can select a path to save the file, but the button is "Move". User expects button  "Save"

![Screenshot 2024-03-22 at 2 59 01 PM](https://github.com/incrediblezayed/file_saver/assets/4512206/ef9fff63-d513-4d49-82d3-c3f0677f1564)

[(As celvinren wrote )](https://github.com/incrediblezayed/file_saver/pull/90) there is necessary small change in one line code for iOS.

I think it should be fixed.

**Comment by incrediblezayed** [comment]
Done!
