### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [incrediblezayed/file_saver#2]
First of all, thanks for creating this awesome plugin ❤️ It works great on web!

## Problem

The package README indicates that the plugin is working on Windows, however, it seems that it does not for me.

For me, Windows Flutter apps crash whenever I call `FileSaver.instance.saveFile`. They simply freeze and after a while the Flutter logs indicate "Lost connection to device."

---

As I am not sure if this is known / how to triage it, I figured I would create this issue.

**Comment by incrediblezayed** [comment]
Okay thanks for reporting, I'll look into it asap.

**Comment by incrediblezayed** [comment]
@creativecreatorormaybenot Can you give more details? I tested it just now and it's working fine.

**Comment by creativecreatorormaybenot** [comment]
@incrediblezayed I am currently not running the project anymore (granted I opened this issue 2 months ago). So if noone can reproduce it, I presume you can close it for now. I would let you know if I experience it again.

**Comment by incrediblezayed** [comment]
@creativecreatorormaybenot really sorry for delayed responsible, I was busy with sone tests.

**Comment by MalikSamiAwan** [comment]
@incrediblezayed is it solved its not working for me on windows
var bytes=excel.encode();
      await storeFileAsBytes(Uint8List.fromList(bytes??[]),'xlsx',MimeType.MICROSOFTEXCEL,context,);
      
      `Future<bool> storeFileAsBytes(Uint8List bytes, String fileFormat, MimeType type,BuildContext context,{String? fileCustomName}) async {


  try {
    pprint('file url = $bytes');
    String filename=generateTimeStampString();
    if(fileCustomName!=null){
      filename=fileCustomName;
    }

      if(kIsWeb){
        var result = await FileSaver.instance
            .saveFile('$filename', bytes, fileFormat, mimeType: type);
        pprint(result, 2);
      }else if (Platform.isAndroid ||
          Platform.isIOS) {
        var result = await FileSaver.instance
            .saveAs('$filename', bytes, fileFormat,type);
        pprint(result, 2);
      } else {
        var result = await FileSaver.instance
            .saveFile('$filename', bytes, fileFormat, mimeType: type);
        pprint(result, 2);
        String path = filename;
        path = 'Dowload/' + path;
        await showSimpleDialog(context: context,title: 'SuccessFully! Downloaded',content: "$path");
      }
      return true;

  } catch (e) {
    pprint('for web');
    pprint(e);
    pprint(e);
    await showSimpleDialog(context: context,title: 'Something Went Wrong!');
    return false;
  }
}
//get current date as random string to save file
String generateTimeStampString(){
  DateTime today = new DateTime.now();
  String dateSlug ="${today.year.toString()}-${today.month.toString().padLeft(2,'0')}-${today.day.toString().padLeft(2,'0')} ${today.hour.toString()}:${today.minute.toString()}:${today.second.toString()}:${today.microsecond.toString()}";
  return dateSlug;
}`
