### ISSUE TITLE
Wrong or missing file extension when calling saveAs()

### ISSUE THREAD

**Issue by Albert-Jan** [incrediblezayed/file_saver#20]
Whenever you open the .saveAs() and try to save a file with a custom extension, it will still save as a .json file.
`await FileSaver.instance.saveAs(fileName, data, 'custom123', MimeType.JSON)`

When you set the MimeType to OTHER, it saves without an extension.
`await FileSaver.instance.saveAs(fileName, data, 'custom123', MimeType.OTHER)`

I've only tried this code on Android.

**Comment by incrediblezayed** [comment]
Hello,
Thank You for using my package,
I'll try to reproduce your issue and will get back to you.
Thanks

**Comment by incrediblezayed** [comment]
Hey, Thank You so much for pointing it out, Fixed this issue in version 0.1.0
