### ISSUE TITLE
Module 'file_saver' not found

### ISSUE THREAD

**Issue by mrmostafaei** [incrediblezayed/file_saver#21]
when run on ios simulator :
Error output from Xcode build:
↳
    objc[25292]: Class AMSupportURLConnectionDelegate is implemented in both
    /usr/lib/libauthinstall.dylib (0x20246ab90) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
    (0x1081ec2c8). One of the two will be used. Which one is undefined.
    objc[25292]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib
    (0x20246abe0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice
    (0x1081ec318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **

Xcode's output:
../ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal
    error: module 'file_saver' not found
    @import file_saver;

**Comment by incrediblezayed** [comment]
Hello,
Thank You for using my package,
Have you tried running 'pod install/update' inside the ios folder of your project?

**Comment by incrediblezayed** [comment]
I think you've not properly installed everything, please connect me on Twitter if the issue is not resolved - @incrediblezayed is also my twitter handle
