### ISSUE TITLE
The plugin `file_saver` requires your app to be migrated to the Android embedding v2.

### ISSUE THREAD

**Issue by AmanuelYosief** [incrediblezayed/file_saver#24]
Warning now appears, and end up failing testing and builds, that I perform on CodeMagic platform even though when I'm using ignore deprecated packages command.

**Comment by incrediblezayed** [comment]
Hi, have you migrated your app to android embedding v2? because this plugin has been on android embedding v2 since the beginning, I'll almost have to recreate the whole thing just for android embedding v1

**Comment by AmanuelYosief** [comment]
Solved issue, i believe this was due to upgrading to a new flutter packages. The app is currently using an pre flutter 2 version and hasn't migrated to 2 alongside all the packages. 

Thanks!
