### ISSUE TITLE
build issue in master branch

### ISSUE THREAD

**Issue by selvam920** [incrediblezayed/file_saver#25]
[C:\Users\sksso\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_saver-0.0.12\android\src\main\kotlin\com\one\file_saver\FileSaverPlugin.kt](): (39, 39): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

**Comment by incrediblezayed** [comment]
Hello, Thank You for using my package, can you share some more details and an error log so that I can work on it.

**Comment by selvam920** [comment]
i'm getting that error only in flutter master branch

**Comment by incrediblezayed** [comment]
I mean can you share the error log? And any specific reason to use it from git? I'm updating everything now so if you tell me the log, I might be able to fix it by today

**Comment by incrediblezayed** [comment]
Hello, Please upgrade to v 0.1.0 and check
