### ISSUE TITLE
if mimeType is MimeType.OTHER, saveAs will append file extension twice

### ISSUE THREAD

**Issue by ameerfayiz** [incrediblezayed/file_saver#27]
ForIOS , if MimeType.OTHER is given as memetype then file extension is added twice.. like "image.png.png"  but for every other memetype , the issue is not reproducing.. and issue is not reproducing for android too.

**Comment by incrediblezayed** [comment]
I'll cross check and will let you know.

**Comment by ToniHeiss** [comment]
Any update on this?

**Comment by chandlery54** [comment]
We are having this same issue. Saving the file extension twice when using a custom extension with `MimeType.OTHER`. 

Has there been any attempt to fix this?

**Comment by D40298008** [comment]
Same issue here.

**Comment by incrediblezayed** [comment]
Hi, I'll update mostly this week, I've gotten busy with certain personal issues.

**Comment by incrediblezayed** [comment]
Hi, please check now, I suggest not giving extension with the file name, please test and let me know
