### ISSUE TITLE
Can't open saved file

### ISSUE THREAD

**Issue by bibash28** [incrediblezayed/file_saver#30]
I cannot programmatically open the 'Saved As' file in android and ios.  It worked with 'Saved' file I have tested in android and ios only.

I am using the following package. It gives me an access error.
https://pub.dev/packages/open_file

**Comment by bibash28** [comment]
ElevatedButton(
      onPressed: () async {
        var message = {'date': "bibash"};
        String path = await FileSaver.instance.saveAs(
            "bibash",
            Uint8List.fromList(message.toString().runes.toList()),
            "txt",
            MimeType.TEXT);
        await OpenFile.open(path);
      },
      child: const Text("Save As"),
    )

**Comment by incrediblezayed** [comment]
Ok, Can you share the full log?

**Comment by javieritis** [comment]
I have the same problem! in Android 8 works fine, but in Android11, cant open the pdf whit "OpenFile"

**Comment by incrediblezayed** [comment]
I think that might be issue with the other package, it'll be a big help if you share the log

**Comment by incrediblezayed** [comment]
Hello, can you please share the log? @bibash28

**Comment by bibash28** [comment]
Execution failed for task ':file_saver:compileDebugKotlin'

@incrediblezayed

**Comment by incrediblezayed** [comment]
Hey are you using the latest version I deployed 2 days ago? 0.1.1?

**Comment by bibash28** [comment]
Not yet.. i will let u know

**Comment by bibash28** [comment]
it works now..
