### ISSUE TITLE
file_saver-0.1.0 Build error : Type mismatch

### ISSUE THREAD

**Issue by shafieesh** [incrediblezayed/file_saver#32]
I cannot build for android on the latest flutter beta version (details attached below).

Gradle error :
e: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\file_saver-0.1.0\android\src\main\kotlin\com\one\file_saver\FileSaverPlugin.kt: (31, 39): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

FAILURE: Build failed with an exception.

Flutter:
Flutter 2.12.0-4.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 680962aa75 (6 days ago) • 2022-03-16 13:46:03 -0700
Engine • revision e9f57b5d0f
Tools • Dart 2.17.0 (build 2.17.0-182.1.beta) • DevTools 2.11.1

**Comment by incrediblezayed** [comment]
I think it's because you're using beta, please wait till I migrate to beta actually

**Comment by sshipman** [comment]
This is happening to me now after upgrading to Flutter 3

**Comment by sshipman** [comment]
I've fixed it locally by changing the onAttachedToEngine function in FileSaverPlugin.kt like so:

`
    override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        if (pluginBinding != null) {
            Log.d(tag, "Already Initialized")
        }
        pluginBinding = flutterPluginBinding
        val messenger = flutterPluginBinding.binaryMessenger
        methodChannel = MethodChannel(messenger, "file_saver")
        methodChannel?.setMethodCallHandler(this)
    }
`

**Comment by ollydixon** [comment]
@incrediblezayed they released 3.0 today in stable, you need to push an update asap!

**Comment by incrediblezayed** [comment]
> @incrediblezayed they released 3.0 today in stable, need an update asap!

Yes, please use git version for now, I'll push an update to pub.dev too, use the latest commit, it will work

**Comment by incrediblezayed** [comment]
Fixes are coming to pub.dev tonight or tomorrow
