### ISSUE TITLE
file_saver: ^0.1.0 gradle:7.1.0 can not load

### ISSUE THREAD

**Issue by zjyhll** [incrediblezayed/file_saver#36]
A problem occurred configuring project ':file_saver'.
> Could not resolve all artifacts for configuration ':file_saver:classpath'.
   > Could not resolve io.grpc:grpc-api:[1.21.1].
     Required by:
         project :file_saver > com.android.tools.build:gradle:7.1.0 > io.grpc:grpc-core:1.21.1
      > Failed to list versions for io.grpc:grpc-api.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/io/grpc/grpc-api/maven-metadata.xml.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/io/grpc/grpc-api/maven-metadata.xml'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve io.netty:netty-codec-http2:[4.1.34.Final].
     Required by:
         project :file_saver > com.android.tools.build:gradle:7.1.0 > io.grpc:grpc-netty:1.21.1
      > Failed to list versions for io.netty:netty-codec-http2.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml.
            > Could not HEAD 'https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

 
**https://repo.maven.apache.org/maven2/io/netty/netty-codec-http2/maven-metadata.xml Its certificate has expired**

**Comment by incrediblezayed** [comment]
Fixes are coming to pub.dev tonight or tomorrow
