### ISSUE TITLE
Issue in flutter 3.0.0 with kt

### ISSUE THREAD

**Issue by EDnny12** [incrediblezayed/file_saver#38]
I can't run my app with this issue.

flutter/.pub-cache/hosted/pub.dartlang.org/file_saver-0.1.0/android/src/main/kotlin/com/one/file_saver/FileSaverPlugin.kt: (31, 39): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

**Comment by yehorh** [comment]
duplicate #32
temporary workaround to clone the pull request and add it to the `pubspec.yaml`
```yaml
  file_saver:
    path: packages/file_saver
```

**Comment by bibash28** [comment]
When will you push the latest version that works with flutter 3? @incrediblezayed

Thanks in advance...

**Comment by incrediblezayed** [comment]
Fixes are coming to pub.dev tonight or tomorrow
