### ISSUE TITLE
_openFileManager crashes app when Cancel button is clicked

### ISSUE THREAD

**Issue by EmirSoza** [incrediblezayed/file_saver#39]
Flutter 2.10.3
iPhone12 Pro Max simulator + iPhone 12 Pro real device

await FileSaver.instance
          .saveAs(fileName, response.bodyBytes, '.pdf', MimeType.PDF)
          .whenComplete(() => print("DONE"));
          
This works great when I save the file to the storage. But if click to Cancel on the left top, the app crashes and on real device unable to open the app again :)

I checked the package and saw that:
_openFileManager crashes app because when cancel clicked _path! returns null which means definitely will definitely break the app.  ("Null check operator used on a null value" is the exact error)
What I've done further to check if it works (not good idea to manipulate packages but just for testing purposes):
I changed _openFileManager function a little bit like:
return _path ?? "";  instead of  return _path!;

This worked great. Can you please fix the error?
Btw, thanks for the great package. I highly appreciate your work.
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-05-16 at 16 28 48](https://user-images.githubusercontent.com/48845452/168616428-fd9ac19f-63d5-45df-a596-7e12db04598e.png)

**Comment by incrediblezayed** [comment]
I'll look into it, and I'm pushing an update tonight or tomorrow to the pub.dev, Please check once again and let me know
