### ISSUE TITLE
Can't save on mobile

### ISSUE THREAD

**Issue by FRANIAZA** [incrediblezayed/file_saver#4]
Works perfectly on web. I am testing it on my Android device and it keeps giving me this error, although the permissions are granted:
```
FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/Restaurapp QR Download.png' (OS Error: Operation not permitted, errno = 1)
```
My code looks like this:
```dart
_screenshotController.capture(delay: Duration(milliseconds: 10)).then((Uint8List? screenshot) async{
              if(screenshot != null){
                if (!kIsWeb) {
                  if (Platform.isIOS || Platform.isAndroid) {
                    bool status = await Permission.storage.isGranted;
                    if (!status) await Permission.storage.request();

                    status = await Permission.storage.isGranted;

                    if(status)
                      await FileSaver.instance.saveFile('Restaurapp QR Download', screenshot, 'png');
                  }
                }else{
                  await FileSaver.instance.saveFile('Restaurapp QR Download', screenshot, 'png');
                }

              }else{
                generateSnackBar(false, S.of(context).failedDownloadText, context);
              }
```

Am I doing something wrong?

**Comment by deandreamatias** [comment]
Hi,
Do you try a filename without spaces? like `Restaurapp_QR_Download.png`
You can add a flutter doctor -v too, to get more info about your develop environment

**Comment by FRANIAZA** [comment]
Hi,
No I have not. I am now only using this package to save files on web. On mobile I opted for image_gallery_saver as it best suites my needs (it displays downloaded images in the gallery which is more intuitive for the user to find).
Thank you for your reply

**Comment by incrediblezayed** [comment]
Hello @FRANIAZA, Sorry for the delayed response, I was busy with some tests, I've added some more features and added a saveAs method to open a file manager to save file. Can you show me your AndroidManifest.xml?
