### ISSUE TITLE
Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected in the line C:\AndroidStudio\flutter\.pub-cache\hosted\pub.dartlang.org\file_saver-0.1.0\android\src\main\kotlin\com\one\file_saver\FileSaverPlugin.kt line(30,31)

### ISSUE THREAD

**Issue by nilotpalkapri** [incrediblezayed/file_saver#40]
It is causing build failure
I found the  error in the specified file 
Error Line: 
methodChannel = MethodChannel(messenger, "file_saver")

My Solution: 
messenger?.let{
        	methodChannel = MethodChannel(messenger, "file_saver")
        	methodChannel?.setMethodCallHandler(this)
	  }

**Comment by matthewwong525** [comment]
I started seeing this as well when i upgraded to Flutter 3

**Comment by Chandio763** [comment]
Facing same issue,  please upgrade the package to flutter 3

**Comment by mrdyman** [comment]
it's come when upgraded flutter to version 3. still waiting to update the package :)

**Comment by kzawadi** [comment]
hahaha, @yahu1031 I found you here man... tirelessly debuging why my at_app on flutter 3 is not compiling ...

**Comment by yahu1031** [comment]
You might have asked me then 🤣

**Comment by kzawadi** [comment]
Man ... they say a good programmers look for issues before filling one.. definitely you will be my one-stop shop

**Comment by ollydixon** [comment]
@incrediblezayed can we get a patch for this?

**Comment by PedroMoreira87** [comment]
![image](https://user-images.githubusercontent.com/63320967/176952189-e359334a-4d0b-4ba8-989f-10f96d7b1926.png)
I tried this solution and it worked

**Comment by ollydixon** [comment]
@PedroMoreira87 it's a bit tricky to this on build servers which do refresh builds each time.

**Comment by yahu1031** [comment]
https://github.com/incrediblezayed/file_saver/issues/40#issuecomment-1148810119 this is current patch you can use for build @ollydixon @PedroMoreira87

**Comment by ollydixon** [comment]
@yahu1031 I see that but it's not safe to use "main" commits for building production apps.

**Comment by yahu1031** [comment]
@ollydixon Yes, But the main branch always doesn't go with unstable code. This branch generally referred to production. When they fix things, The stable code goes here. So, No worries to use it. Incase you still feel it may break, Then pick up the working reference hash/commit id and refer it in pubspec instead of main. So it will only take the code you referred to.

**Comment by incrediblezayed** [comment]
Fixes are coming to pub.dev tonight or tomorrow
