### ISSUE TITLE
[Web] Missing extension

### ISSUE THREAD

**Issue by leoshusar** [incrediblezayed/file_saver#42]
Hi, I see you are adding extension to method channel arguments [here](https://github.com/incrediblezayed/file_saver/blob/c0ea84007896c6014c72785a8bcde0e9c53dc804/lib/file_saver.dart#L226), but you are not retrieving it [here](https://github.com/incrediblezayed/file_saver/blob/c0ea84007896c6014c72785a8bcde0e9c53dc804/lib/file_saver_web.dart#L28), so the file is saved without extension.

**Comment by incrediblezayed** [comment]
Hi @leoshusar, Please test the latest version and let me know

**Comment by bhendee** [comment]
I'm using the latest version, and I see extensions on Chrome but not Firefox. No extensions on Chrome if I don't specify a mime type. Seems like the extension on Chrome might be luck from the mime type?

**Comment by leoshusar** [comment]
@incrediblezayed thanks, works for me!

For now I'll keep this open for @bhendee.
In my case I'm using both `ext: 'json'` and `MimeType.json`, tried Chrome and Firefox Dev, no issue in both of them.

**Comment by bhendee** [comment]
I'm using `ext: 'txt'` (also tried `.txt`) and `MimeType.text`. Still no extension on Firefox downloads.

**Comment by incrediblezayed** [comment]
@bhendee I'll test it out and let you know

**Comment by Bungeefan** [comment]
We are still impacted by this bug even in the latest version.
The extension is still missing from the actual filename set in the `download` attribute.

https://github.com/incrediblezayed/file_saver/blob/b7e050b079c62b505155e4968efc2c34a156a278/lib/file_saver_web.dart#L50-L52

However, I provided a PR (#70) which should finally fix this.
