### ISSUE TITLE
Execution failed for task ':file_saver:compileDebugKotlin'.

### ISSUE THREAD

**Issue by apoorvpandey** [incrediblezayed/file_saver#44]
Launching lib\main_stage.dart on Pixel 4a in debug mode...
lib\main_stage.dart:1
Parameter format not correct -
e: C:\Workspace\flutter\.pub-cache\hosted\pub.dartlang.org\file_saver-0.1.0\android\src\main\kotlin\com\one\file_saver\FileSaverPlugin.kt: (30, 25): Smart cast to 'FlutterPlugin.FlutterPluginBinding' is impossible, because 'pluginBinding' is a mutable property that could have been changed by this time
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_saver:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 12s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

![image](https://user-images.githubusercontent.com/17758959/174112110-5f7afd0e-487e-4bf8-9c17-0f99ea5c5d32.png)

**Comment by exonent** [comment]
Same!

**Comment by clintonksang** [comment]
@exonent @apoorvpandey same error, I believe the package hasn't been upgraded to flutter  3

**Comment by apoorvpandey** [comment]
I have tried this same with flutter version 2.10.4 🥲

**Comment by clintonksang** [comment]
@apoorvpandey checkout to branch `fix/compileDebugKotlin` and import it on your pubspec, see if it works

**Comment by Dr-Usman** [comment]
Facing same problem on Flutter 3.0. Any updated version?

**Comment by apoorvpandey** [comment]
> Experiencing the same issue, are there any fixes or workarounds?

I just fixed by
Deleting these folders
.idea, pubspec.loc, .gradle, run flutter cache repair
Do let me know if this fixes for you

**Comment by Dr-Usman** [comment]
@apoorvpandey I have tried that but still same error occur and can't able to run or create build app.

**Comment by Myzel394** [comment]
@apoorvpandey this didn't work for me :(

**Comment by incrediblezayed** [comment]
Can you guys please upgrade to latest version and check?

**Comment by apoorvpandey** [comment]
Fixed (Forgot the solution)

**Comment by exonent** [comment]
The solution was:

1. flutter clean
2. flutter pub cache repair
3. flutter pub cache clean
4. cd ios
5. rm -f Podfile.lock
6. pod deintegrate
7. pod install
8. cd ..
9. flutter pub get
