### ISSUE TITLE
File saver is not working on Flutter 3

### ISSUE THREAD

**Issue by Katekko** [incrediblezayed/file_saver#46]
\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\file_saver-0.1.0\android\src\main\kotlin\com\one\file_saver\FileSaverPlugin.kt: (31, 39): Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':file_saver:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ScratchX98** [comment]
Same

**Comment by riberman** [comment]
To build and no show errors in Flutter 3.0.4 for dev mode, change line 30 in file FileSaverPlugin.kt
`val messenger = pluginBinding?.binaryMessenger`
to
`val messenger = pluginBinding?.binaryMessenger!!`

**Comment by incrediblezayed** [comment]
Fixes are coming to pub.dev tonight or tomorrow
