### ISSUE TITLE
[BUG] 'Future<Directory?>' is not a subtype of type 'FutureOr<Directory>' [mac OS]

### ISSUE THREAD

**Issue by shofizone** [incrediblezayed/file_saver#5]
I am getting this error on mac os.

This is the sample code.
```
() async {
                      var path = await FileSaver.instance.saveFile(
                        DateTime.now().toIso8601String(),
                        pngBytes,
                        "png",
                        mimeType: MimeType.PNG,
                      );
                      debugPrint("$path");
                    }

```
and this the error I am getting in the console.

```
flutter: type 'Future<Directory?>' is not a subtype of type 'FutureOr<Directory>' in type cast
flutter: null

```

**Comment by incrediblezayed** [comment]
> I am getting this error on mac os.
> 
> This is the sample code.
> 
> ```
> () async {
>                       var path = await FileSaver.instance.saveFile(
>                         DateTime.now().toIso8601String(),
>                         pngBytes,
>                         "png",
>                         mimeType: MimeType.PNG,
>                       );
>                       debugPrint("$path");
>                     }
> ```
> 
> and this the error I am getting in the console.
> 
> ```
> flutter: type 'Future<Directory?>' is not a subtype of type 'FutureOr<Directory>' in type cast
> flutter: null
> ```

Okay thanks, I'll look into it asap.

**Comment by incrediblezayed** [comment]
This issue is fixed in the recent update, thanks for reporting.
