### ISSUE TITLE
saveFile produces empty file after upgrade to 0.2.0 (Web)

### ISSUE THREAD

**Issue by nitelow** [incrediblezayed/file_saver#57]
After I upgraded from v0.1.1 to v0.2.0 the resulting file on web release is empty.

Code before:
    
    final Uint8List data = Uint8List.fromList(csv.codeUnits);

    MimeType type = MimeType.CSV;

    await FileSaver.instance.saveFile(
      "inventory.csv",
      data,
      "csv",
      mimeType: type);

After upgrade:

    final Uint8List data = Uint8List.fromList(csv.codeUnits);

    MimeType type = MimeType.csv;

    await FileSaver.instance.saveFile(
      name: "inventory.csv",
      bytes: data,
      ext: "csv",
      mimeType: type);

Flutter/Dart versions are 3.7.8/2.19.5

**Comment by incrediblezayed** [comment]
Okay, sure, I'll test it out, I just wanna know 1 thing, from where are you generating/getting the file

**Comment by nitelow** [comment]
Thanks a lot! :)

The "csv" variable is a string filled with the csv-formatted data. Debugging shows me correct contents of "csv" and "data" so these shouldn't be the issue.

**Comment by nitelow** [comment]
https://github.com/incrediblezayed/file_saver/blob/54aba56e6d3df700925340407fa6dfba2eadcbbd/lib/file_saver_web.dart#L45

This line seems to cause the problem: Blob should take "fileModel.bytes" as argument instead of "fileModel.name".

**Comment by incrediblezayed** [comment]
> Thanks a lot! :)
> 
> https://github.com/incrediblezayed/file_saver/blob/54aba56e6d3df700925340407fa6dfba2eadcbbd/lib/file_saver_web.dart#L45
> 
> This line seems to cause the problem: Blob should take "fileModel.bytes" as argument instead of "fileModel.name".
> Currently it writes only the file name into the file but not the contents.

Oops, a silly mistake, actually I was trying something new for web and that might have messed it up

**Comment by jthlim** [comment]
Came here to report the same issue with 0.2.0 -- seems like the fix is quite straight forward :)

**Comment by incrediblezayed** [comment]
> Came here to report the same issue with 0.2.0 -- seems like the fix is quite straight forward :)

This will be fixed tonight don't worry

**Comment by nitelow** [comment]
Thanks for the update!

I'll close the issue :-)

**Comment by incrediblezayed** [comment]
> Thanks for the update!
> 
> I'll close the issue :-)

Thank you as well, keep supporting please
