### ISSUE TITLE
Download file without extension

### ISSUE THREAD

**Issue by KrakenTyio** [incrediblezayed/file_saver#59]
When i use `saveFile` and i not define ext or define as empty, your script try to extract extension, but when is not present, let say bc its shell script for linux. It always add dot on end.

this line https://github.com/incrediblezayed/file_saver/blob/27ff2740685ef17f035606cc6372903f8411ba0f/lib/src/utils/helpers.dart#L64

alway add empty dot on end when stricted and also parsed extension is not present.

**Comment by incrediblezayed** [comment]
Hmmm, I'm returning empty extension from that method now, is that alright?

**Comment by KrakenTyio** [comment]
but empty extension is without dot (`.`) and for me it returns something like `application.` and that dont on end is not extension, but not needed separator

**Comment by KrakenTyio** [comment]
yes, correct. when no extension is provided, just return name without dot

**Comment by incrediblezayed** [comment]
> yes, correct. when no extension is provided, just return name without dot

Okay then, I'll release in an hour or so, please test and let me know

**Comment by incrediblezayed** [comment]
Hi @KrakenTyio, did you test it? can we close this?

**Comment by KrakenTyio** [comment]
> Hi @KrakenTyio, did you test it? can we close this?

sorry no,in final i used own written code

**Comment by incrediblezayed** [comment]
@KrakenTyio Ok then, I'll close this issue, thank you for mentioning though
