### ISSUE TITLE
Headers for download

### ISSUE THREAD

**Issue by KrakenTyio** [incrediblezayed/file_saver#60]
Will be nice to possibility propagate headers to Client get, bc. second parameter for `httpClient.get` allow headers
in this line
https://github.com/incrediblezayed/file_saver/blob/27ff2740685ef17f035606cc6372903f8411ba0f/lib/src/utils/helpers.dart#L29

thx

**Comment by incrediblezayed** [comment]
Hey, yeah sorry I missed that, I'll add it in a day

**Comment by incrediblezayed** [comment]
@KrakenTyio , I'm adding headers with the next update, please test in production and reopen this issue if has any problems
