### ISSUE TITLE
Update http package

### ISSUE THREAD

**Issue by patachi** [incrediblezayed/file_saver#63]
we finally reached version 1.0.0 for the HTTP package.

**Comment by incrediblezayed** [comment]
@patachi I'd love to, but latest http version will create conflict with other packages which are still on 0.13, but I'll do it asap regardless of that

**Comment by urielvexi** [comment]
While they upgrade to version 1.0.0 you can use this
```
dependency_overrides:
    http: ^1.0.0
```

**Comment by incrediblezayed** [comment]
> While they upgrade to version 1.0.0 you can use this
> 
> ```
> dependency_overrides:
>     http: ^1.0.0
> ```

Ok Ok, I'll do it soon

**Comment by jokraft** [comment]
Is there still anything preventing the version bump?

**Comment by incrediblezayed** [comment]
> Is there still anything preventing the version bump?

Not anymore, I'll update today, Thank You
