### ISSUE TITLE
How do I download from Firebase Storage?

### ISSUE THREAD

**Issue by KimAloy** [incrediblezayed/file_saver#7]
Hi,
I'm interested in using file_saver package to download an image from Firebase Storage for flutter web.

First off, thanks for your incredible efforts. I'd like to use file_saver package to download from Firebase Storage. 

I think that an example on how to do this will boost the usability of the file_saver package because most flutter coders use Firebase.

I'll greatly appreciate when you show me how to download.

Thank you & Blessings,
Kimbowa Aloysius,
Uganda

**Comment by incrediblezayed** [comment]
Hello,
Thank You So much for your suggestion and question, 
I'll add an example for downloading a file from firebase as well,
I won't be able to add the entire code, but I will add the firebase code from my own closed source code.

Blessings and regards.

**Comment by incrediblezayed** [comment]
@KimAloy 
Here is the code: 
`  Future<void> downloadFile() async {
    Reference _fileReference =
        FirebaseStorage.instance.ref().child('your/path/toFile.jpg');
    Uint8List bytes = await _fileReference.getData();
    await FileSaver.instance.saveAs("fileName", bytes, ".jpg", MimeType.JPEG);
  }`

I guess I can close the issue now.
