### ISSUE TITLE
Handling Api Error status in LinkDetails 

### ISSUE THREAD

**Issue by tusharbhambere** [incrediblezayed/file_saver#82]
Description:- In LinkDetail passing url which getting 404 how we can handle this?

```
String path2 = await FileSaver.instance.saveFile(
        name: '${tCcll}_$valueType.pdf',
        link: LinkDetails(
          link: url,
        ),
        mimeType: MimeType.pdf,
      );
```
Currently its return path=>  /storage/emulated/0/Android/data/******.com/files/NS2000054_Quotation.pdf 
empty pdf saved

*Requirement
Need to handle All Error status code in  LinkDetails so pdf will not save and throw error

**Comment by incrediblezayed** [comment]
Is it possible for you to handle and create PR? I'm a bit busy with stuff so... @tusharbhambere

**Comment by incrediblezayed** [comment]
Just add a try catch block with the method call, throwing the exception directly back to the caller instead of handling locally, you'll find your issues
