### ISSUE TITLE
FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/file.csv' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by YxLee611** [incrediblezayed/file_saver#9]
Hi, I'm currently facing this issue on Android 11, can anyone help on this?
Error:
FileSystemException: Cannot open file, path = '/storage/emulated/0/Download/file.csv' (OS Error: Operation not permitted, errno = 1)

**Comment by YxLee611** [comment]
await fileSaver.saveAs(
      "csv-${DateTime.now()}",
      Uint8List.fromList(bytes),
      "csv",
      type
    );

**Comment by incrediblezayed** [comment]
Hello, I've updated the plugin and fixed this issue, please check version 0.0.10
